try [
    error "wow"
] catch [
    log('lol, error:', err)
]